baseURL = "https://www.saadnsyed.com/"
languageCode = "en-us"
theme = "anatole"
publishDir   = "docs"
enableRobotsTXT = true

# Google Analytics
googleAnalytics = "UA-190447443-1"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Saad Syed"
author = "Saad Syed"
description = "Cofounder at Flow. Biker. Runner. Wannabe Chef."
profilePicture = "images/headshot.jpg"
doNotLoadAnimations = true
favicon = "favicons/"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

[[params.socialIcons]]
icon = "fas fa-tools"
title = "Flow"
url = "https://enterflow.app/?utm_source=saadnsyed.com&utm_medium=referral"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/saadnsyed/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/saadnsyed"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "Instagram"
url = "https://instagram.com/saadnsyed"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:saadnsyed@gmail.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Tags"
  weight = 300
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "Reading List"
  weight = 300
  identifier = "reading-list"
  url = "/reading-list/"
