baseURL = "http://example.org/"
languageCode = "en-us"
theme = "anatole"

[params]
title = "Saad Syed"
author = "Saad Syed"
description = "Software Engineer. Biker. Runner. Wannabe chef. Cofounder at www.enterflow.app"
profilePicture = "images/headshot.png"
doNotLoadAnimations = true

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/saadnsyed/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/saadnsyed"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://instagram.com/saadnsyed"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:saadnsyed@gmail.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"
