baseURL = "http://example.org/"
languageCode = "en-us"
theme = "anatole"
publishDir   = "docs"

[params]
title = "Saad Syed"
author = "Saad Syed"
description = "Cofounder at Flow. Biker. Runner. Wannabe Chef."
profilePicture = "images/headshot.png"
doNotLoadAnimations = true
favicon = "favicons/"

[[params.socialIcons]]
icon = "fas fa-tools"
title = "Flow"
url = "https://enterflow.app/?utm_source=flow&utm_medium=saad-personal-site"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/saadnsyed/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/saadnsyed"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "Instagram"
url = "https://instagram.com/saadnsyed"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:saadnsyed@gmail.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Tags"
  weight = 300
  identifier = "tags"
  url = "/tags/"
